name: Tests

on: push

jobs:
  lint:
    name: Run tests
    if: "!contains(github.event.commits.message, '[skip ci]')"
    runs-on: ubuntu-latest
    container: 'node:12-alpine'
    steps:
    - uses: actions/checkout@v1
    - run: npm ci
    - run: npm build --if-present
    - run: npm test